# Generated by Django 4.1.1 on 2022-09-17 11:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('phone_number', models.TextField(max_length=10)),
                ('county', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=30)),
                ('town', models.TextField(max_length=30)),
                ('street', models.TextField(max_length=30)),
                ('House_no', models.TextField(max_length=30)),
                ('profileimg', models.ImageField(default='man.png', upload_to='User_profile_images')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 9, 17, 14, 4, 57, 733613))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
