# Generated by Django 4.1.1 on 2022-09-26 12:46

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_alter_user_profile_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner_platters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('price_small', models.IntegerField()),
                ('price_large', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regular_Pizza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('cheese_small', models.IntegerField()),
                ('cheese_large', models.IntegerField()),
                ('price_1_topping_small', models.IntegerField()),
                ('price_1_topping_large', models.IntegerField()),
                ('price_2_topping_small', models.IntegerField()),
                ('price_2_topping_large', models.IntegerField()),
                ('price_3_topping_small', models.IntegerField()),
                ('price_3_topping_large', models.IntegerField()),
                ('price_special_small', models.IntegerField()),
                ('price_special_large', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sicilian_Pizza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('cheese_small', models.IntegerField()),
                ('cheese_large', models.IntegerField()),
                ('price_1_item_small', models.IntegerField()),
                ('price_1_item_large', models.IntegerField()),
                ('price_2_item_small', models.IntegerField()),
                ('price_2_item_large', models.IntegerField()),
                ('price_3_item_small', models.IntegerField()),
                ('price_3_item_large', models.IntegerField()),
                ('price_special_small', models.IntegerField()),
                ('price_special_large', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('price_small', models.IntegerField()),
                ('price_large', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 15, 46, 28, 804615)),
        ),
    ]
