# Generated by Django 4.1.1 on 2022-09-27 09:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0003_dinner_platters_pasta_regular_pizza_salads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner_platter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('price_small', models.IntegerField()),
                ('price_large', models.IntegerField()),
                ('itemimg', models.ImageField(default='not-found.png', upload_to='Item_images')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('pizza_type', models.TextField(max_length=10)),
                ('no_of_toppings', models.IntegerField()),
                ('small', models.IntegerField()),
                ('large', models.IntegerField()),
                ('itemimg', models.ImageField(default='not-found.png', upload_to='Item_images')),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('price', models.IntegerField()),
                ('itemimg', models.ImageField(default='not-found.png', upload_to='Item_images')),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('price_small', models.IntegerField()),
                ('price_large', models.IntegerField()),
                ('itemimg', models.ImageField(upload_to='Item_images')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('price', models.IntegerField()),
                ('itemimg', models.ImageField(default='not-found.png', upload_to='Item_images')),
            ],
        ),
        migrations.DeleteModel(
            name='Dinner_platters',
        ),
        migrations.DeleteModel(
            name='Regular_Pizza',
        ),
        migrations.DeleteModel(
            name='Salads',
        ),
        migrations.DeleteModel(
            name='Sicilian_Pizza',
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
        migrations.AddField(
            model_name='pasta',
            name='itemimg',
            field=models.ImageField(default='not-found.png', upload_to='Item_images'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 12, 9, 53, 132113)),
        ),
    ]
