# Generated by Django 4.1.1 on 2022-09-27 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0004_dinner_platter_pizza_salad_sub_topping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 9, 49, 188998)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('status', models.TextField(max_length=10)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.dinner_platter')),
            ],
        ),
    ]
