# Generated by Django 4.1.1 on 2022-09-30 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0008_remove_order_items_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='item',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 11, 32, 42, 303239)),
        ),
    ]
